### ISSUE TITLE
Roadmap to v1.1.0

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#8]
The list of stuff to achieve Spress v1.1.0. Each feature will be explained separately in a issue:

- [x] **IO API** for to interact with users. See ["New in Spress 1.1: IO API"](http://spress.yosymfony.com/news/2014/05/11/new-in-spress-1-1-io-api/).
- [x] **Environment configurations**: we can set options for various environments like development and production: See proposal #9.
- [x] **Spress Core**: See proposal #13.
- [x] **Improve the plugins manager**: See proposal #11.
- [x] **Plugin scaffolding**: new command for scafolding plugins.
- [x] **Built-in server** for to see the result as we work. See proposal #15.
- [ ] **Spress-import**: **(Moved to Spress 2.0 roadmap)** a tool for importing blog from sources like Wordpress or Tumblr.
- [x] **Update documentation**

**Comment by lury** [comment]
Spress-import :+1:

**Comment by yosymfony** [comment]
Yes. I'm get on with it after Spress 2.0.0 has been released
