### ISSUE TITLE
The roadmap of Spress 2.2.0

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#95]
Below, the list of new features for version 2.2.0:
- [x] Allow default attributes on "pages" collection.
- [x] Extend option "avoid_renderizer" to types of files or directories. See #91.
- [x] A set of commands for managing add-ons: install and update themes and plugins. See #96.
- [x] Sort terms in taxonomy generator.
- [x] Support for themes.
- [x] IO review: allow to use verbosity level at `write` method. Additionally, two new methods will be included: `overwrite` and `askChoice`. The former overwrites a previous message to the output. The latter makes questions with a predefined values.

Doc tasks:
- [x] Review [IO API](http://spress.yosymfony.com/docs/developers/io-api/) page for including new methods.
- [X] Review [Command plugins page](http://spress.yosymfony.com/docs/developers/command-plugins/) for including `getSpress` of `CommandEnvironmentInterface`.
- [x] Review [developer page](http://spress.yosymfony.com/docs/developers/) for updating the plugin-installer version.
- [x] Review the [theme page](http://spress.yosymfony.com/docs/themes/). See #98 and #91.
- [x] Review [How it work](http://spress.yosymfony.com/docs/how-it-works/) page. Include new commands. See #96.
- [x] Review the [collection] page. See #93.
